# Generated by Django 2.1.5 on 2019-03-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2019-03-09')),
                ('due_date', models.DateField(default='2019-03-09')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
